#!/bin/bash

set -euxo pipefail

readonly IMAGE_NAMESPACE='iluvzhouying'
readonly IMAGE_NAME='shift-scheduler-app'
readonly TAG=$(git log -1 --pretty=%h)
readonly IMAGE="${IMAGE_NAMESPACE}/${IMAGE_NAME}:${TAG}"

npm test 

npm run build

docker build -t ${IMAGE} . 

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 

docker push ${IMAGE}